# Generated by Django 3.2.9 on 2021-12-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uy', '0002_remove_new_home_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_home',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
