# Generated by Django 3.2.9 on 2021-12-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uy', '0008_auto_20211219_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_home',
            name='user',
            field=models.ManyToManyField(to='uy.Profile'),
        ),
    ]
