# Generated by Django 3.2.9 on 2021-12-19 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uy', '0009_alter_new_home_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_home',
            name='user',
        ),
        migrations.AddField(
            model_name='new_home',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
